//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gageas.Lutea.HTTPController.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gageas.Lutea.HTTPController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   body,html
        ///{
        ///    height : 100%;
        ///    margin : 0px;
        ///    padding : 0px;
        ///}
        ///
        ///table#layoutTable
        ///{
        ///    border : solid Transparent 5px;
        ///    border-bottom-width : 25px; /* Chromeで画面内にポップアップが出るので広めにとる */
        ///    border-right-width : 0px;
        ///    border-collapse :separate;
        ///    width : 100%;
        ///    height : 100%;
        ///}
        ///
        ///img
        ///{
        ///    border:0px;
        ///    margin:0px 5px 5px 0px;
        ///}
        ///
        ///div#img_over
        ///{
        ///    position:absolute;
        ///    z-index:3;
        ///    width:166px;
        ///    height:166px;
        ///    border : outset 2px #aaa; /*aaa*/
        ///       bo [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defalut_css {
            get {
                return ResourceManager.GetString("defalut_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var _file_name = null;
        ///var _playlistQuery = null;
        ///
        ///var loadData_id = 0;
        ///var loadPlaylist_id = 0;
        ///
        ///var delayedPlaylistBuilder = null;
        ///var delayedPlaylistBuilderPos = 0;
        ///
        ///var commitQueryTimer = null;
        ///
        ///var loadDataAjax = null;
        ///var loadPlaylistAjax = null;
        ///
        ///var emphasized_element = null;
        ///
        ///var Controller = {
        ///    Play: function () { hitPath(&quot;./?mode=control&amp;operation=play&quot;); },
        ///    Stop: function () { hitPath(&quot;./?mode=control&amp;operation=stop&quot;); },
        ///    Next: function () { hitPath(&quot;./?mode=control [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string main_js {
            get {
                return ResourceManager.GetString("main_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Lutea&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html; charset=utf8&quot; /&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///&lt;!script type=&quot;text/javascript&quot; src=&quot;https://github.com/gageas/JSTitleFormatting/raw/master/tf.js&quot;&gt;&lt;!/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///%%SCRIPT%%
        ///&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///function TFIf(env, args) {
        ///    var cond = args[0];
        ///    var a = args[1];
        ///    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_html {
            get {
                return ResourceManager.GetString("template_html", resourceCulture);
            }
        }
    }
}
